/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.106
 * Generated at: 2025-07-07 08:34:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class AboutUs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>About Us - TechParts</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Segoe UI', sans-serif;\r\n");
      out.write("            background-color: #f0f4f8;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .about-container {\r\n");
      out.write("            max-width: 1000px;\r\n");
      out.write("            margin: 60px auto;\r\n");
      out.write("            background-color: #ffffff;\r\n");
      out.write("            padding: 40px 50px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 10px 25px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .about-header {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .about-header h1 {\r\n");
      out.write("            color: #1d4ed8;\r\n");
      out.write("            font-size: 36px;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .about-header p {\r\n");
      out.write("            color: #555;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            max-width: 700px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .about-section {\r\n");
      out.write("            margin-top: 40px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .about-section h2 {\r\n");
      out.write("            color: #333;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .about-section p {\r\n");
      out.write("            color: #666;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            line-height: 1.7;\r\n");
      out.write("            margin-bottom: 25px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .features-list {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(230px, 1fr));\r\n");
      out.write("            gap: 20px;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .feature-box {\r\n");
      out.write("            background-color: #f8fafc;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.05);\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .feature-box h3 {\r\n");
      out.write("            color: #1d4ed8;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .feature-box p {\r\n");
      out.write("            color: #444;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer-note {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #999;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            margin-top: 40px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .header {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 20px 40px;\r\n");
      out.write("            background: white;\r\n");
      out.write("            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo h2 {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            color: #2563eb;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-links {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 25px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-links a {\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: #374151;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-links a.active-link {\r\n");
      out.write("            color: #2563eb;\r\n");
      out.write("           font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("        .search-bar {\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-bar input {\r\n");
      out.write("            padding: 8px 32px 8px 30px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-bar::before {\r\n");
      out.write("            content: '🔍';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            left: 10px;\r\n");
      out.write("            top: 7px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            color: #666;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cart {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cart::after {\r\n");
      out.write("            content: '0';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: -10px;\r\n");
      out.write("            right: -10px;\r\n");
      out.write("            background: red;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-size: 10px;\r\n");
      out.write("            width: 16px;\r\n");
      out.write("            height: 16px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-btn a {\r\n");
      out.write("            background: #2563eb;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 8px 16px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .main-content {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 50px 80px;\r\n");
      out.write("            background: #e8f0fc;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .text-content {\r\n");
      out.write("            max-width: 50%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .text-content h1 {\r\n");
      out.write("            font-size: 48px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            color: #111827;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .text-content .highlight {\r\n");
      out.write("            color: #2563eb;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .text-content p {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            color: #555;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .buttons {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn {\r\n");
      out.write("            padding: 12px 24px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn.dark {\r\n");
      out.write("            background-color: #0f172a;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn.light {\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            color: #0f172a;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .image-content {\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("         <style>\r\n");
      out.write("    /* ... your existing styles ... */\r\n");
      out.write("\r\n");
      out.write("    .dropdown {\r\n");
      out.write("         position: relative;\r\n");
      out.write("            display: inline-block;* Make it obvious it's clickable */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .dropdown-content {\r\n");
      out.write("       display: none;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            min-width: 220px;\r\n");
      out.write("            top: 38px;\r\n");
      out.write("            margin-left:3%;\r\n");
      out.write("            margin-top:15%\r\n");
      out.write("            left: 0;\r\n");
      out.write("            box-shadow: 0px 8px 16px rgba(0, 0, 0, 0.15);\r\n");
      out.write("            z-index: 999;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .dropdown-content a {\r\n");
      out.write("       color: #333;\r\n");
      out.write("            padding: 12px 16px;\r\n");
      out.write("            display: block;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .dropdown-content a:hover {\r\n");
      out.write("        background-color: #f1f1f1;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Instead of showing on hover, show when .show class is added */\r\n");
      out.write("    .dropdown.show .dropdown-content {\r\n");
      out.write("       display: block;\r\n");
      out.write("    }\r\n");
      out.write("     .dropdown:hover .dropdown-content {\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("              \r\n");
      out.write("        \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("    <div class=\"logo\">\r\n");
      out.write("        <img src=\"images/logo.png\" alt=\"logo\" width=\"40\" height=\"40\">\r\n");
      out.write("        <h2>TechParts</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"nav-links\">\r\n");
      out.write("        <a href=\"Home.jsp\">Home</a>\r\n");
      out.write("        <a href=\"AboutUs.jsp\">About Us</a>\r\n");
      out.write("        <div class=\"dropdown\">\r\n");
      out.write("            <span class=\"dropbtn\">All Products</span>\r\n");
      out.write("            <div class=\"dropdown-content\">\r\n");
      out.write("                <a href=\"Laptops.jsp\">Laptops</a>\r\n");
      out.write("                <a href=\"LaptopAccessories.jsp\">Laptop Accessories</a>\r\n");
      out.write("                <a href=\"computerAccessories.jsp\">Desktop & Accessories</a>\r\n");
      out.write("                <a href=\"cctvcamera.jsp\">CCTV Camera & Accessories</a>\r\n");
      out.write("                \r\n");
      out.write("                <a href=\"printers.jsp\">Printers</a>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"Services.jsp\">Services</a>\r\n");
      out.write("        <a href=\"Paymentmethod.jsp\">Payment Methods</a>\r\n");
      out.write("        <a href=\"contact.jsp\">Contact Us</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div style=\"display: flex; align-items: center; gap: 15px;\">\r\n");
      out.write("        <div class=\"search-bar\">\r\n");
      out.write("            <input type=\"text\" placeholder=\"Search products...\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"cart\">🛒</div>\r\n");
      out.write("        <div class=\"login-btn\">\r\n");
      out.write("            <a href=\"Login.jsp\">Login</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"about-container\">\r\n");
      out.write("        <div class=\"about-header\">\r\n");
      out.write("            <h1>About TechParts</h1>\r\n");
      out.write("            <p>Your one-stop solution for computer spare parts, accessories, and repair management.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"about-section\">\r\n");
      out.write("            <h2>Who We Are</h2>\r\n");
      out.write("            <p>TechParts is a reliable and fast-growing platform for managing and sourcing a wide range of computer spare parts, components, and accessories. Whether you're an IT technician, business owner, or computer enthusiast, we’re here to help you find quality parts with ease.</p>\r\n");
      out.write("\r\n");
      out.write("            <h2>What We Offer</h2>\r\n");
      out.write("            <div class=\"features-list\">\r\n");
      out.write("                <div class=\"feature-box\">\r\n");
      out.write("                    <h3>Inventory Management</h3>\r\n");
      out.write("                    <p>Track stock levels, manage product availability, and prevent shortages.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"feature-box\">\r\n");
      out.write("                    <h3>Supplier Management</h3>\r\n");
      out.write("                    <p>Connect and manage trusted suppliers for consistent product flow.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"feature-box\">\r\n");
      out.write("                    <h3>Order & Sales System</h3>\r\n");
      out.write("                    <p>Handle orders efficiently and keep records of every transaction.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"feature-box\">\r\n");
      out.write("                    <h3>Finance Monitoring</h3>\r\n");
      out.write("                    <p>Track your expenses and earnings to ensure financial stability.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <h2>Our Mission</h2>\r\n");
      out.write("            <p>To simplify and automate spare parts management while delivering exceptional service and reliability to our users.</p>\r\n");
      out.write("\r\n");
      out.write("            <h2>Contact Us</h2>\r\n");
      out.write("            <p>Have questions or need support? Reach us at <strong>support@techparts.com</strong> or call <strong>+94 77 123 4567</strong>.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer-note\">\r\n");
      out.write("            &copy; 2025 TechParts System. All rights reserved.\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("<script>\r\n");
      out.write("document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("  const dropdown = document.querySelector('.dropdown');\r\n");
      out.write("  const dropbtn = dropdown.querySelector('.dropbtn');\r\n");
      out.write("\r\n");
      out.write("  dropbtn.addEventListener('click', function(e) {\r\n");
      out.write("    e.stopPropagation();\r\n");
      out.write("    dropdown.classList.toggle('show');\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("  // Close dropdown if clicked outside\r\n");
      out.write("  document.addEventListener('click', function() {\r\n");
      out.write("    dropdown.classList.remove('show');\r\n");
      out.write("  });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
