/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.106
 * Generated at: 2025-07-01 08:07:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Contactus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Contact Us - TechParts</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Segoe UI', sans-serif;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            background-color: #f9fafb;\r\n");
      out.write("        }\r\n");
      out.write("        .header {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 20px 40px;\r\n");
      out.write("            background: white;\r\n");
      out.write("            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 1000;\r\n");
      out.write("        }\r\n");
      out.write("        .logo {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .logo h2 {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            color: #2563eb;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-links {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 25px;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-links a,\r\n");
      out.write("        .dropbtn {\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: #374151;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            background: none;\r\n");
      out.write("            border: none;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-links a.active-link {\r\n");
      out.write("            color: #2563eb;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("        .dropdown {\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("        .dropdown-content {\r\n");
      out.write("            display: none;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            min-width: 220px;\r\n");
      out.write("            top: 100%;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            box-shadow: 0px 8px 16px rgba(0, 0, 0, 0.15);\r\n");
      out.write("            z-index: 1500;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("        }\r\n");
      out.write("        .dropdown-content a {\r\n");
      out.write("            color: #333;\r\n");
      out.write("            padding: 12px 16px;\r\n");
      out.write("            display: block;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("        .dropdown-content a:hover {\r\n");
      out.write("            background-color: #f1f1f1;\r\n");
      out.write("        }\r\n");
      out.write("        .dropdown.show .dropdown-content {\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("        .header-right {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        .search-bar {\r\n");
      out.write("            padding: 8px 12px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("        }\r\n");
      out.write("        .cart-icon {\r\n");
      out.write("            font-size: 22px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: #374151;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        .cart-icon:hover {\r\n");
      out.write("            color: #2563eb;\r\n");
      out.write("        }\r\n");
      out.write("        .login-btn {\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: #374151;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("        .login-btn:hover {\r\n");
      out.write("            color: #2563eb;\r\n");
      out.write("        }\r\n");
      out.write("        .contact-container {\r\n");
      out.write("            max-width: 900px;\r\n");
      out.write("            margin: 40px auto;\r\n");
      out.write("            padding: 0 20px;\r\n");
      out.write("        }\r\n");
      out.write("        h1 {\r\n");
      out.write("            font-size: 32px;\r\n");
      out.write("            color: #1f2937;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        .contact-grid {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: 1fr 1fr;\r\n");
      out.write("            gap: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        .contact-info,\r\n");
      out.write("        .contact-form {\r\n");
      out.write("            background: white;\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.05);\r\n");
      out.write("        }\r\n");
      out.write("        .contact-info h2 {\r\n");
      out.write("            color: #2563eb;\r\n");
      out.write("            margin-top: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .contact-info p {\r\n");
      out.write("            margin: 10px 0;\r\n");
      out.write("            line-height: 1.4;\r\n");
      out.write("        }\r\n");
      out.write("        input,\r\n");
      out.write("        textarea {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            resize: vertical;\r\n");
      out.write("        }\r\n");
      out.write("        button {\r\n");
      out.write("            background-color: #2563eb;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: background-color 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        button:hover {\r\n");
      out.write("            background-color: #1d4ed8;\r\n");
      out.write("        }\r\n");
      out.write("        footer {\r\n");
      out.write("            background-color: #0f172a;\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 20px 10px;\r\n");
      out.write("            margin-top: 40px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("    <div class=\"logo\">\r\n");
      out.write("        <img src=\"images/logo.png\" alt=\"logo\" width=\"40\" height=\"40\">\r\n");
      out.write("        <h2>TechParts</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <nav class=\"nav-links\">\r\n");
      out.write("        <a href=\"Home.jsp\">Home</a>\r\n");
      out.write("        <a href=\"AboutUs.jsp\">About Us</a>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"dropdown\">\r\n");
      out.write("            <button class=\"dropbtn\" type=\"button\">All Products ▼</button>\r\n");
      out.write("            <div class=\"dropdown-content\">\r\n");
      out.write("                <a href=\"laptops.jsp\">Laptops</a>\r\n");
      out.write("                <a href=\"laptopAccessories.jsp\">Laptop Accessories</a>\r\n");
      out.write("                <a href=\"desktopAccessories.jsp\">Desktop & Accessories</a>\r\n");
      out.write("                <a href=\"cctv.jsp\">CCTV Camera & Accessories</a>\r\n");
      out.write("                <a href=\"cameraItems.jsp\">Camera Items</a>\r\n");
      out.write("                <a href=\"printers.jsp\">Printers</a>\r\n");
      out.write("                <a href=\"giftVouchers.jsp\">Gift Vouchers</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"Services.jsp\">Services</a>\r\n");
      out.write("        <a href=\"payment.jsp\">Payment Methods</a>\r\n");
      out.write("        <a class=\"active-link\" href=\"contact.jsp\">Contact Us</a>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"header-right\">\r\n");
      out.write("        <input type=\"text\" placeholder=\"Search products...\" class=\"search-bar\" aria-label=\"Search products\">\r\n");
      out.write("        <a href=\"cart.jsp\" class=\"cart-icon\" aria-label=\"Cart\">🛒</a>\r\n");
      out.write("        <a href=\"Login.jsp\" class=\"login-btn\">Login</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"contact-container\">\r\n");
      out.write("    <h1>Contact Us</h1>\r\n");
      out.write("    <div class=\"contact-grid\">\r\n");
      out.write("        <div class=\"contact-info\">\r\n");
      out.write("            <h2>Head Office</h2>\r\n");
      out.write("            <p>Sell-X Computers (Pvt) Ltd</p>\r\n");
      out.write("            <p>#87/6, Hettigewaththa, Kithulampitiya, Galle, Sri Lanka</p>\r\n");
      out.write("            <p><strong>Phone:</strong> +94 91 20 30000 / +94 112 88 222</p>\r\n");
      out.write("            <p><strong>Email:</strong> support@sellx.lk</p>\r\n");
      out.write("            <p><strong>Working Hours:</strong> Mon - Sat: 9:00AM - 6:00PM</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"contact-form\">\r\n");
      out.write("            <h2>Send a Message</h2>\r\n");
      out.write("            <form action=\"#\" method=\"post\">\r\n");
      out.write("                <input type=\"text\" name=\"name\" placeholder=\"Your Name\" required>\r\n");
      out.write("                <input type=\"email\" name=\"email\" placeholder=\"Your Email\" required>\r\n");
      out.write("                <textarea name=\"message\" rows=\"5\" placeholder=\"Your Message\" required></textarea>\r\n");
      out.write("                <button type=\"submit\">Send</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    &copy; 2025 TechParts. All Rights Reserved.\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("        const dropdown = document.querySelector('.dropdown');\r\n");
      out.write("        const dropbtn = dropdown.querySelector('.dropbtn');\r\n");
      out.write("\r\n");
      out.write("        dropbtn.addEventListener('click', function(e) {\r\n");
      out.write("            e.stopPropagation();\r\n");
      out.write("            dropdown.classList.toggle('show');\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        document.addEventListener('click', function() {\r\n");
      out.write("            dropdown.classList.remove('show');\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
