/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.106
 * Generated at: 2025-07-03 14:56:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.math.BigDecimal;

public final class EditCctvAccessory_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.math.BigDecimal");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    String idParam = request.getParameter("id");
    if (idParam == null || idParam.trim().isEmpty()) {
        response.sendRedirect("ViewCctvAccess.jsp"); // redirect if no id
        return;
    }
    
    int id = 0;
    try {
        id = Integer.parseInt(idParam);
    } catch (NumberFormatException e) {
        response.sendRedirect("ViewCctvAccess.jsp"); // redirect if invalid id
        return;
    }

    // Initialize variables for product info
    String name = "";
    String item_code = "";
    String category = "CCTV Accessory";
    BigDecimal price = BigDecimal.ZERO;
    BigDecimal cash_price = BigDecimal.ZERO;
    String stock_status = "";
    String image_url = "";
    String description = "";
    String brand = "";

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    try {
        Class.forName("com.mysql.jdbc.Driver"); // or com.mysql.cj.jdbc.Driver
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/computer", "root", "ishini2003");
        String sql = "SELECT * FROM cctvaccess WHERE id = ?";
        pst = conn.prepareStatement(sql);
        pst.setInt(1, id);
        rs = pst.executeQuery();

        if (rs.next()) {
            name = rs.getString("name");
            item_code = rs.getString("item_code");
            category = rs.getString("category");
            price = rs.getBigDecimal("price");
            cash_price = rs.getBigDecimal("cash_price");
            stock_status = rs.getString("stock_status");
            image_url = rs.getString("image_url");
            description = rs.getString("description");
            brand = rs.getString("brand");
        } else {
            response.sendRedirect("CiewCctvAccess.jsp"); // no record found, redirect
            return;
        }

    } catch (Exception e) {
        e.printStackTrace();
    } finally {
        if (rs != null) try { rs.close(); } catch (Exception e) {}
        if (pst != null) try { pst.close(); } catch (Exception e) {}
        if (conn != null) try { conn.close(); } catch (Exception e) {}
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Edit CCTV Accessory</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Segoe UI', sans-serif;\r\n");
      out.write("            background-color: #f3f4f6;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 700px;\r\n");
      out.write("            margin: 40px auto;\r\n");
      out.write("            background: white;\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            box-shadow: 0 8px 20px rgba(0,0,0,0.1);\r\n");
      out.write("        }\r\n");
      out.write("        h2 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #1f2937;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        label {\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin-bottom: 8px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #374151;\r\n");
      out.write("        }\r\n");
      out.write("        input[type=\"text\"],\r\n");
      out.write("        input[type=\"number\"],\r\n");
      out.write("        select,\r\n");
      out.write("        textarea {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 10px 14px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            border: 1px solid #cbd5e1;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            background: #f9fafb;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        textarea {\r\n");
      out.write("            resize: vertical;\r\n");
      out.write("        }\r\n");
      out.write("        input[type=\"submit\"] {\r\n");
      out.write("            background-color: #2563eb;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 12px 24px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: background-color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        input[type=\"submit\"]:hover {\r\n");
      out.write("            background-color: #1e40af;\r\n");
      out.write("        }\r\n");
      out.write("        .back-link {\r\n");
      out.write("            display: block;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            color: #374151;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("        .back-link:hover {\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <h2>Edit CCTV Accessory</h2>\r\n");
      out.write("    <form action=\"UpdateCctvAccessoryServlet\" method=\"post\">\r\n");
      out.write("        <input type=\"hidden\" name=\"id\" value=\"");
      out.print( id );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("        <label for=\"name\">Product Name</label>\r\n");
      out.write("        <input type=\"text\" id=\"name\" name=\"name\" value=\"");
      out.print( name );
      out.write("\" required>\r\n");
      out.write("\r\n");
      out.write("        <label for=\"item_code\">Item Code</label>\r\n");
      out.write("        <input type=\"text\" id=\"item_code\" name=\"item_code\" value=\"");
      out.print( item_code );
      out.write("\" required>\r\n");
      out.write("\r\n");
      out.write("        <label for=\"category\">Category</label>\r\n");
      out.write("        <input type=\"text\" id=\"category\" name=\"category\" value=\"");
      out.print( category );
      out.write("\" readonly>\r\n");
      out.write("\r\n");
      out.write("        <label for=\"price\">Price (Rs.)</label>\r\n");
      out.write("        <input type=\"number\" step=\"0.01\" id=\"price\" name=\"price\" value=\"");
      out.print( price );
      out.write("\" required>\r\n");
      out.write("\r\n");
      out.write("        <label for=\"cash_price\">Cash Price (Rs.)</label>\r\n");
      out.write("        <input type=\"number\" step=\"0.01\" id=\"cash_price\" name=\"cash_price\" value=\"");
      out.print( cash_price );
      out.write("\" required>\r\n");
      out.write("\r\n");
      out.write("        <label for=\"stock_status\">Stock Status</label>\r\n");
      out.write("        <select id=\"stock_status\" name=\"stock_status\" required>\r\n");
      out.write("            <option value=\"\">-- Select Status --</option>\r\n");
      out.write("            <option value=\"In Stock\" ");
      out.print( "In Stock".equals(stock_status) ? "selected" : "" );
      out.write(">In Stock</option>\r\n");
      out.write("            <option value=\"Low Stock\" ");
      out.print( "Low Stock".equals(stock_status) ? "selected" : "" );
      out.write(">Low Stock</option>\r\n");
      out.write("            <option value=\"Out of Stock\" ");
      out.print( "Out of Stock".equals(stock_status) ? "selected" : "" );
      out.write(">Out of Stock</option>\r\n");
      out.write("        </select>\r\n");
      out.write("\r\n");
      out.write("        <label for=\"image_url\">Image URL</label>\r\n");
      out.write("        <input type=\"text\" id=\"image_url\" name=\"image_url\" value=\"");
      out.print( image_url );
      out.write("\" required>\r\n");
      out.write("\r\n");
      out.write("        <label for=\"description\">Description</label>\r\n");
      out.write("        <textarea id=\"description\" name=\"description\" rows=\"4\">");
      out.print( description != null ? description : "" );
      out.write("</textarea>\r\n");
      out.write("\r\n");
      out.write("        <label for=\"brand\">Brand</label>\r\n");
      out.write("        <input type=\"text\" id=\"brand\" name=\"brand\" value=\"");
      out.print( brand != null ? brand : "" );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("        <input type=\"submit\" value=\"Update Accessory\">\r\n");
      out.write("    </form>\r\n");
      out.write("    <a href=\"ViewCctvAccess.jsp\" class=\"back-link\">← Back to Accessories List</a>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
