/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.106
 * Generated at: 2025-07-04 06:10:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>TechParts Management System</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Segoe UI', sans-serif;\r\n");
      out.write("            background: #f0f4f8;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .header {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 20px 50px;\r\n");
      out.write("            background: white;\r\n");
      out.write("            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo h2 {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            color: #1d4ed8;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo p {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            color: #666;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-btn a {\r\n");
      out.write("            background: #0f172a;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .main-content {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 50px 80px;\r\n");
      out.write("            background: #e8f0fc;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .text-content {\r\n");
      out.write("            max-width: 50%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .text-content h1 {\r\n");
      out.write("            font-size: 48px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            color: #111827;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .text-content .highlight {\r\n");
      out.write("            color: #2563eb;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .text-content p {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            color: #555;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .buttons {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn {\r\n");
      out.write("            padding: 12px 24px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn.dark {\r\n");
      out.write("            background-color: #0f172a;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn.light {\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            color: #0f172a;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .image-content {\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .image-content img {\r\n");
      out.write("            width: 600px;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            box-shadow: 0 8px 20px rgba(0, 0, 0, 0.15);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tag {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            bottom: 20px;\r\n");
      out.write("            left: 20px;\r\n");
      out.write("            background: white;\r\n");
      out.write("            padding: 12px 20px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tag strong {\r\n");
      out.write("            display: block;\r\n");
      out.write("            color: #1d4ed8;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Duplicate styles removed, kept only one set */\r\n");
      out.write("\r\n");
      out.write("        .header {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 20px 40px;\r\n");
      out.write("            background: white;\r\n");
      out.write("            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo h2 {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            color: #2563eb;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-links {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 25px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-links a {\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: #374151;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-links a.active-link {\r\n");
      out.write("            color: #2563eb;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("        .search-bar {\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-bar input {\r\n");
      out.write("            padding: 8px 32px 8px 30px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-bar::before {\r\n");
      out.write("            content: '🔍';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            left: 10px;\r\n");
      out.write("            top: 7px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            color: #666;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cart {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cart::after {\r\n");
      out.write("            content: '0';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: -10px;\r\n");
      out.write("            right: -10px;\r\n");
      out.write("            background: red;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-size: 10px;\r\n");
      out.write("            width: 16px;\r\n");
      out.write("            height: 16px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-btn a {\r\n");
      out.write("            background: #2563eb;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 8px 16px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .main-content {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 50px 80px;\r\n");
      out.write("            background: #e8f0fc;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .text-content {\r\n");
      out.write("            max-width: 50%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .text-content h1 {\r\n");
      out.write("            font-size: 48px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            color: #111827;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .text-content .highlight {\r\n");
      out.write("            color: #2563eb;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .text-content p {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            color: #555;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .buttons {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn {\r\n");
      out.write("            padding: 12px 24px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn.dark {\r\n");
      out.write("            background-color: #0f172a;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn.light {\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            color: #0f172a;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .image-content {\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .image-content img {\r\n");
      out.write("            width: 600px;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            box-shadow: 0 8px 20px rgba(0, 0, 0, 0.15);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tag {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            bottom: 20px;\r\n");
      out.write("            left: 20px;\r\n");
      out.write("            background: white;\r\n");
      out.write("            padding: 12px 20px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tag strong {\r\n");
      out.write("            display: block;\r\n");
      out.write("            color: #1d4ed8;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dropdown {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dropdown-content {\r\n");
      out.write("            display: none;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            min-width: 220px;\r\n");
      out.write("            top: 38px;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            box-shadow: 0px 8px 16px rgba(0, 0, 0, 0.15);\r\n");
      out.write("            z-index: 999;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dropdown-content a {\r\n");
      out.write("            color: #333;\r\n");
      out.write("            padding: 12px 16px;\r\n");
      out.write("            display: block;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("        .dropdown.show .dropdown-content {\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("        .dropdown-content a:hover {\r\n");
      out.write("            background-color: #f1f1f1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dropdown:hover .dropdown-content {\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("      \r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("    <div class=\"logo\">\r\n");
      out.write("        <img src=\"images/logo.png\" alt=\"logo\" width=\"40\" height=\"40\">\r\n");
      out.write("        <h2>TechParts</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"nav-links\">\r\n");
      out.write("        <a href=\"Home.jsp\">Home</a>\r\n");
      out.write("        <a href=\"AboutUs.jsp\">About Us</a>\r\n");
      out.write("        <div class=\"dropdown\">\r\n");
      out.write("            <span class=\"dropbtn\">All Products</span>\r\n");
      out.write("            <div class=\"dropdown-content\">\r\n");
      out.write("                <a href=\"Laptops.jsp\">Laptops</a>\r\n");
      out.write("                <a href=\"LaptopAccessories.jsp\">Laptop Accessories</a>\r\n");
      out.write("                <a href=\"computerAccessories.jsp\">Desktop & Accessories</a>\r\n");
      out.write("                <a href=\"cctvcamera.jsp\">CCTV Camera & Accessories</a>\r\n");
      out.write("                \r\n");
      out.write("                <a href=\"printers.jsp\">Printers</a>\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"Services.jsp\">Services</a>\r\n");
      out.write("        <a href=\"Paymentmethod.jsp\">Payment Methods</a>\r\n");
      out.write("        <a href=\"Contactus.jsp\">Contact Us</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div style=\"display: flex; align-items: center; gap: 15px;\">\r\n");
      out.write("       \r\n");
      out.write("        <div class=\"cart\">🛒</div>\r\n");
      out.write("        <div class=\"login-btn\">\r\n");
      out.write("            <a href=\"Login.jsp\">Login</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"main-content\">\r\n");
      out.write("    <div class=\"text-content\">\r\n");
      out.write("        <h1>Manage Your <span class=\"highlight\">Tech Inventory</span></h1>\r\n");
      out.write("        <p>Streamline your computer spare parts management with our comprehensive inventory system. Track stock, manage suppliers, and grow your business.</p>\r\n");
      out.write("        <div class=\"buttons\">\r\n");
      out.write("            <a href=\"Register.jsp\" class=\"btn dark\">Get Started</a>\r\n");
      out.write("            <a href=\"about.jsp\" class=\"btn light\">Learn More</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"image-content\">\r\n");
      out.write("        <img src=\"images/motherboard.jpeg\" alt=\"Motherboard Image\">\r\n");
      out.write("        <div class=\"tag\">\r\n");
      out.write("            <strong>⚡ Fast & Efficient</strong>\r\n");
      out.write("            Real-time updates\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Features Section -->\r\n");
      out.write("<div style=\"text-align: center; padding: 60px 20px; background: #fff;\">\r\n");
      out.write("    <h2 style=\"font-size: 32px; margin-bottom: 15px; color: #111827;\">Everything You Need</h2>\r\n");
      out.write("    <p style=\"font-size: 18px; color: #555; margin-bottom: 50px;\">\r\n");
      out.write("        Our comprehensive platform provides all the tools you need to manage your computer parts inventory efficiently.\r\n");
      out.write("    </p>\r\n");
      out.write("\r\n");
      out.write("    <div style=\"display: flex; justify-content: center; flex-wrap: wrap; gap: 30px;\">\r\n");
      out.write("        <!-- Card 1 -->\r\n");
      out.write("        <div style=\"width: 240px; background: #fff; border-radius: 12px; box-shadow: 0 2px 10px rgba(0,0,0,0.05); padding: 30px; text-align: center;\">\r\n");
      out.write("            <div style=\"background: #e0edff; width: 60px; height: 60px; border-radius: 50%; margin: 0 auto 15px;\">\r\n");
      out.write("                <img src=\"images/inventory.png\" alt=\"Inventory\" style=\"width: 32px; margin-top: 14px;\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <h3 style=\"font-size: 18px; color: #111827; margin-bottom: 10px;\">Inventory Management</h3>\r\n");
      out.write("            <p style=\"font-size: 14px; color: #555;\">Track and manage your spare parts inventory with ease</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Card 2 -->\r\n");
      out.write("        <div style=\"width: 240px; background: #fff; border-radius: 12px; box-shadow: 0 2px 10px rgba(0,0,0,0.05); padding: 30px; text-align: center;\">\r\n");
      out.write("            <div style=\"background: #e0edff; width: 60px; height: 60px; border-radius: 50%; margin: 0 auto 15px;\">\r\n");
      out.write("                <img src=\"images/supplier.png\" alt=\"Supplier\" style=\"width: 32px; margin-top: 14px;\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <h3 style=\"font-size: 18px; color: #111827; margin-bottom: 10px;\">Supplier Management</h3>\r\n");
      out.write("            <p style=\"font-size: 14px; color: #555;\">Maintain relationships with your trusted suppliers</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Card 3 -->\r\n");
      out.write("        <div style=\"width: 240px; background: #fff; border-radius: 12px; box-shadow: 0 2px 10px rgba(0,0,0,0.05); padding: 30px; text-align: center;\">\r\n");
      out.write("            <div style=\"background: #e0edff; width: 60px; height: 60px; border-radius: 50%; margin: 0 auto 15px;\">\r\n");
      out.write("                <img src=\"images/sales.png\" alt=\"Sales\" style=\"width: 32px; margin-top: 14px;\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <h3 style=\"font-size: 18px; color: #111827; margin-bottom: 10px;\">Sales Analytics</h3>\r\n");
      out.write("            <p style=\"font-size: 14px; color: #555;\">Monitor your sales performance and trends</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Card 4 -->\r\n");
      out.write("        <div style=\"width: 240px; background: #fff; border-radius: 12px; box-shadow: 0 2px 10px rgba(0,0,0,0.05); padding: 30px; text-align: center;\">\r\n");
      out.write("            <div style=\"background: #e0edff; width: 60px; height: 60px; border-radius: 50%; margin: 0 auto 15px;\">\r\n");
      out.write("                <img src=\"images/security.png\" alt=\"Security\" style=\"width: 32px; margin-top: 14px;\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <h3 style=\"font-size: 18px; color: #111827; margin-bottom: 10px;\">Secure & Reliable</h3>\r\n");
      out.write("            <p style=\"font-size: 14px; color: #555;\">Your data is protected with enterprise-grade security</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Built for the Future Section -->\r\n");
      out.write("<div style=\"display: flex; align-items: center; justify-content: center; padding: 60px 80px; gap: 50px; background: #fff; flex-wrap: wrap;\">\r\n");
      out.write("    <div style=\"flex: 1;\">\r\n");
      out.write("        <img src=\"images/code.jpeg\" alt=\"Code Image\" style=\"width: 100%; border-radius: 12px; box-shadow: 0 8px 20px rgba(0, 0, 0, 0.15);\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div style=\"flex: 1; max-width: 500px;\">\r\n");
      out.write("        <h2 style=\"font-size: 28px; color: #111827; margin-bottom: 15px;\">Built for the Future</h2>\r\n");
      out.write("        <p style=\"color: #555; margin-bottom: 25px;\">\r\n");
      out.write("            Our system uses cutting-edge technology to ensure your inventory management is always up-to-date, secure, and scalable as your business grows.\r\n");
      out.write("        </p>\r\n");
      out.write("        <ul style=\"list-style: none; padding: 0;\">\r\n");
      out.write("            <li style=\"margin-bottom: 10px; color: #10b981;\">✔ Enterprise-grade security</li>\r\n");
      out.write("            <li style=\"margin-bottom: 10px; color: #3b82f6;\">✔ Real-time synchronization</li>\r\n");
      out.write("            <li style=\"color: #8b5cf6;\">✔ Advanced analytics</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Call to Action -->\r\n");
      out.write("<div style=\"background-color: #2563eb; color: white; text-align: center; padding: 60px 20px;\">\r\n");
      out.write("    <h2 style=\"font-size: 28px; margin-bottom: 15px;\">Ready to Get Started?</h2>\r\n");
      out.write("    <p style=\"font-size: 16px; margin-bottom: 30px;\">Join thousands of businesses already using TechParts to manage their inventory.</p>\r\n");
      out.write("    <a href=\"Register.jsp\" style=\"background-color: white; color: #0f172a; padding: 12px 24px; border-radius: 8px; text-decoration: none; font-weight: bold;\">\r\n");
      out.write("        ➔ Sign Up Now\r\n");
      out.write("    </a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<div style=\"background-color: #0f172a; color: white; padding: 20px 50px; display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap;\">\r\n");
      out.write("    <div style=\"display: flex; align-items: center; gap: 10px;\">\r\n");
      out.write("        <img src=\"images/logo.png\" alt=\"logo\" width=\"30\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <strong style=\"font-size: 16px;\">TechParts</strong><br>\r\n");
      out.write("            <small style=\"color: #94a3b8;\">Management System</small>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div style=\"font-size: 14px;\">© 2024 TechParts. All rights reserved.</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("	  const dropdown = document.querySelector('.dropdown');\r\n");
      out.write("	  const dropbtn = dropdown.querySelector('.dropbtn');\r\n");
      out.write("\r\n");
      out.write("	  dropbtn.addEventListener('click', function(e) {\r\n");
      out.write("	    e.stopPropagation();\r\n");
      out.write("	    dropdown.classList.toggle('show');\r\n");
      out.write("	  });\r\n");
      out.write("\r\n");
      out.write("	  document.addEventListener('click', function() {\r\n");
      out.write("	    dropdown.classList.remove('show');\r\n");
      out.write("	  });\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
