/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.106
 * Generated at: 2025-07-06 06:10:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import ComputerPackage.CartItem;

public final class LaptopAccessories_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("ComputerPackage.CartItem");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>All Laptop Accessories - TechParts</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            background: #f9f9f9;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .header {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 20px 40px;\r\n");
      out.write("            background: white;\r\n");
      out.write("            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo h2 {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            color: #2563eb;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-links {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 25px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-links a {\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: #374151;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-links a.active-link {\r\n");
      out.write("            color: #2563eb;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dropdown {\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dropbtn {\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            color: #374151;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dropdown-content {\r\n");
      out.write("            display: none;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            min-width: 220px;\r\n");
      out.write("            top: 30px;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            box-shadow: 0px 8px 16px rgba(0, 0, 0, 0.15);\r\n");
      out.write("            z-index: 999;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dropdown-content a {\r\n");
      out.write("            color: #333;\r\n");
      out.write("            padding: 12px 16px;\r\n");
      out.write("            display: block;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dropdown-content a:hover {\r\n");
      out.write("            background-color: #f1f1f1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dropdown:hover .dropdown-content {\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cart {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cart-count {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: -10px;\r\n");
      out.write("            right: -10px;\r\n");
      out.write("            background: red;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-size: 10px;\r\n");
      out.write("            width: 16px;\r\n");
      out.write("            height: 16px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-btn a {\r\n");
      out.write("            background: #2563eb;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 8px 16px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .content {\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h2 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .top-bar {\r\n");
      out.write("            background: #fff;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 2px 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .top-bar input[type=\"text\"] {\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            width: 300px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .accessory-grid {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\r\n");
      out.write("            gap: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card {\r\n");
      out.write("            background: #fff;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            box-shadow: 0 4px 10px rgba(0,0,0,0.1);\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            transition: transform 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card:hover {\r\n");
      out.write("            transform: translateY(-5px);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card img {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 160px;\r\n");
      out.write("            object-fit: contain;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card h3 {\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            margin: 10px 0 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .price, .cash-price {\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            margin: 5px 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .price {\r\n");
      out.write("            color: #e11d48;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cash-price {\r\n");
      out.write("            color: #16a34a;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .status {\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            padding: 4px 8px;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            margin: 5px 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .in-stock {\r\n");
      out.write("            background-color: #10b981;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .low-stock {\r\n");
      out.write("            background-color: #facc15;\r\n");
      out.write("            color: black;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .out-stock {\r\n");
      out.write("            background-color: #ef4444;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-buttons {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-buttons button {\r\n");
      out.write("            padding: 8px 12px;\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .add-cart { background-color: #6b7280; color: white; }\r\n");
      out.write("        .view-more { background-color: #2563eb; color: white; }\r\n");
      out.write("        .buy-now { background-color: #dc2626; color: white; }\r\n");
      out.write("        .add-cart:hover { background-color: #4b5563; }\r\n");
      out.write("        .view-more:hover { background-color: #1d4ed8; }\r\n");
      out.write("        .buy-now:hover { background-color: #b91c1c; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <div class=\"header\">\r\n");
      out.write("        <div class=\"logo\">\r\n");
      out.write("            <img src=\"images/logo.png\" alt=\"logo\" width=\"40\" height=\"40\">\r\n");
      out.write("            <h2>TechParts</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"nav-links\">\r\n");
      out.write("            <a href=\"Home.jsp\">Home</a>\r\n");
      out.write("            <a href=\"AboutUs.jsp\">About Us</a>\r\n");
      out.write("            <div class=\"dropdown\">\r\n");
      out.write("                <span class=\"dropbtn\">All Products</span>\r\n");
      out.write("                <div class=\"dropdown-content\">\r\n");
      out.write("                    <a href=\"Laptops.jsp\">Laptops</a>\r\n");
      out.write("                    <a href=\"LaptopAccessories.jsp\">Laptop Accessories</a>\r\n");
      out.write("                    <a href=\"desktopAccessories.jsp\">Desktop & Accessories</a>\r\n");
      out.write("                    <a href=\"cctvcamera.jsp\">CCTV Camera & Accessories</a>\r\n");
      out.write("                    <a href=\"printers.jsp\">Printers</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <a href=\"Services.jsp\">Services</a>\r\n");
      out.write("            <a href=\"Paymentmethod.jsp\">Payment Methods</a>\r\n");
      out.write("            <a href=\"Contactus.jsp\">Contact Us</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"display: flex; align-items: center; gap: 15px;\">\r\n");
      out.write("            <a href=\"ViewCart.jsp\" class=\"cart\" style=\"text-decoration: none; color: inherit;\">\r\n");
      out.write("                ð\r\n");
      out.write("                ");

                    List<CartItem> cart = (List<CartItem>) session.getAttribute("cart");
                    int count = 0;
                    if (cart != null) {
                        for (CartItem item : cart) {
                            count += item.getQuantity();
                        }
                    }
                
      out.write("\r\n");
      out.write("                <span class=\"cart-count\">");
      out.print( count );
      out.write("</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"login-btn\">\r\n");
      out.write("                <a href=\"Login.jsp\">Login</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("    <h2>ALL LAPTOP ACCESSORIES</h2>\r\n");
      out.write("    <div class=\"top-bar\">\r\n");
      out.write("        <input type=\"text\" id=\"searchInput\" placeholder=\"Search accessories...\" onkeyup=\"filterAccessories()\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"accessory-grid\" id=\"accessoryGrid\">\r\n");
      out.write("        ");
 
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/computer", "root", "ishini2003");
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM products WHERE category IS NOT NULL");
            while (rs.next()) {
                String statusClass = "in-stock";
                String stockStatus = rs.getString("stock_status");
                if(stockStatus.equalsIgnoreCase("Low Stock")) statusClass = "low-stock";
                else if(stockStatus.equalsIgnoreCase("Out of Stock")) statusClass = "out-stock";
        
      out.write("\r\n");
      out.write("        <div class=\"card\" data-name=\"");
      out.print( rs.getString("name") );
      out.write("\" data-category=\"");
      out.print( rs.getString("category") );
      out.write("\">\r\n");
      out.write("            <img src=\"");
      out.print( rs.getString("image_url") );
      out.write("\" alt=\"Accessory Image\">\r\n");
      out.write("            <h3>");
      out.print( rs.getString("name") );
      out.write("</h3>\r\n");
      out.write("            <p>");
      out.print( rs.getString("category") );
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print( rs.getString("item_code") );
      out.write("</p>\r\n");
      out.write("            <p class=\"price\">Rs. ");
      out.print( rs.getDouble("price") );
      out.write("</p>\r\n");
      out.write("            <p class=\"cash-price\">Cash Price: Rs. ");
      out.print( rs.getDouble("cash_price") );
      out.write("</p>\r\n");
      out.write("            <span class=\"status ");
      out.print( statusClass );
      out.write('"');
      out.write('>');
      out.print( rs.getString("stock_status") );
      out.write("</span>\r\n");
      out.write("            <div class=\"card-buttons\">\r\n");
      out.write("                <form action=\"AddToCartServlet\" method=\"post\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"id\" value=\"");
      out.print( rs.getInt("id") );
      out.write("\" />\r\n");
      out.write("                    <input type=\"hidden\" name=\"name\" value=\"");
      out.print( rs.getString("name") );
      out.write("\" />\r\n");
      out.write("                    <input type=\"hidden\" name=\"price\" value=\"");
      out.print( rs.getDouble("price") );
      out.write("\" />\r\n");
      out.write("                    <input type=\"hidden\" name=\"quantity\" value=\"1\" />\r\n");
      out.write("                    <button type=\"submit\" class=\"add-cart\">Add to Cart</button>\r\n");
      out.write("                </form>\r\n");
      out.write("                <a href=\"ViewLaptopAccessDetails.jsp?id=");
      out.print( rs.getInt("id") );
      out.write("\" class=\"view-more\" style=\"text-decoration: none; padding: 8px 12px; border-radius: 6px;\">View</a>\r\n");
      out.write("                <form action=\"BuyNowServlet\" method=\"post\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"id\" value=\"");
      out.print( rs.getInt("id") );
      out.write("\" />\r\n");
      out.write("                    <input type=\"hidden\" name=\"name\" value=\"");
      out.print( rs.getString("name") );
      out.write("\" />\r\n");
      out.write("                    <input type=\"hidden\" name=\"price\" value=\"");
      out.print( rs.getDouble("price") );
      out.write("\" />\r\n");
      out.write("                    <input type=\"hidden\" name=\"quantity\" value=\"1\" />\r\n");
      out.write("                    <button type=\"submit\" class=\"buy-now\">Buy Now</button>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 
            } 
            conn.close();
        } catch(Exception e) {
            out.print("Error: " + e.getMessage());
        }
        
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("    function filterAccessories() {\r\n");
      out.write("        const input = document.getElementById(\"searchInput\").value.toLowerCase();\r\n");
      out.write("        const cards = document.querySelectorAll(\".card\");\r\n");
      out.write("        cards.forEach(card => {\r\n");
      out.write("            const name = card.dataset.name.toLowerCase();\r\n");
      out.write("            const category = card.dataset.category.toLowerCase();\r\n");
      out.write("            const match = name.includes(input) || category.includes(input);\r\n");
      out.write("            card.style.display = match ? \"block\" : \"none\";\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
