/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.106
 * Generated at: 2025-07-01 15:13:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\r\n");
      out.write("  <title>TechParts Login</title>\r\n");
      out.write("  <script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-gray-100 flex items-center justify-center min-h-screen\">\r\n");
      out.write("\r\n");
      out.write("  <div class=\"bg-white p-8 rounded-lg shadow-md w-full max-w-sm\">\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    <div class=\"flex items-center mb-6 space-x-2\">\r\n");
      out.write("      <div class=\"bg-blue-500 text-white p-2 rounded-full\">\r\n");
      out.write("        <svg xmlns=\"http://www.w3.org/2000/svg\" class=\"h-5 w-5\" fill=\"none\" viewBox=\"0 0 24 24\"\r\n");
      out.write("          stroke=\"currentColor\">\r\n");
      out.write("          <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\"\r\n");
      out.write("            d=\"M9.75 17h4.5M12 3v14m-7.5 4.5h15a.75.75 0 00.75-.75v-15a.75.75 0 00-.75-.75h-15a.75.75 0 00-.75.75v15a.75.75 0 00.75.75z\"/>\r\n");
      out.write("        </svg>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div>\r\n");
      out.write("        <h1 class=\"text-lg font-bold text-gray-900\">TechParts</h1>\r\n");
      out.write("        <p class=\"text-sm text-gray-500\" id=\"form-title\">Login to continue</p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Tabs -->\r\n");
      out.write("    <div class=\"flex bg-gray-100 rounded-md overflow-hidden mb-4\">\r\n");
      out.write("      <button id=\"userBtn\" class=\"w-1/2 py-2 bg-white font-semibold text-blue-600\">User Login</button>\r\n");
      out.write("      <button id=\"managerBtn\" class=\"w-1/2 py-2 text-gray-500 hover:text-blue-600\">Manager Login</button>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Error message (from servlet) -->\r\n");
      out.write("    ");

      String error = (String) request.getAttribute("errorMessage");
      if (error != null) {
    
      out.write("\r\n");
      out.write("    <div class=\"text-red-600 text-sm mb-4 text-center font-medium\">\r\n");
      out.write("      ");
      out.print( error );
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- User Login Form -->\r\n");
      out.write("    <form id=\"userForm\" action=\"UserLoginServlet\" method=\"post\">\r\n");
      out.write("      <div class=\"mb-4\">\r\n");
      out.write("        <label class=\"block text-sm font-medium text-gray-700\">Email</label>\r\n");
      out.write("        <input type=\"email\" name=\"email\" placeholder=\"Enter your email\"\r\n");
      out.write("          class=\"mt-1 w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-400\"/>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"mb-6\">\r\n");
      out.write("        <label class=\"block text-sm font-medium text-gray-700\">Password</label>\r\n");
      out.write("        <input type=\"password\" name=\"password\" placeholder=\"Enter your password\"\r\n");
      out.write("          class=\"mt-1 w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-400\"/>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <button type=\"submit\"\r\n");
      out.write("        class=\"w-full bg-black text-white py-2 rounded-md hover:bg-gray-900 transition duration-200\">\r\n");
      out.write("        Login as User\r\n");
      out.write("      </button>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    <!-- Manager Login Form (Frontend only) -->\r\n");
      out.write("    <form id=\"managerForm\" onsubmit=\"return handleManagerLogin()\" style=\"display: none;\">\r\n");
      out.write("      <div class=\"mb-4\">\r\n");
      out.write("        <label class=\"block text-sm font-medium text-gray-700\">Username</label>\r\n");
      out.write("        <input type=\"text\" id=\"managerUsername\" placeholder=\"Enter your username\"\r\n");
      out.write("          class=\"mt-1 w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-400\"/>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"mb-6\">\r\n");
      out.write("        <label class=\"block text-sm font-medium text-gray-700\">Password</label>\r\n");
      out.write("        <input type=\"password\" id=\"managerPassword\" placeholder=\"Enter your password\"\r\n");
      out.write("          class=\"mt-1 w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-400\"/>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <button type=\"submit\"\r\n");
      out.write("        class=\"w-full bg-blue-600 text-white py-2 rounded-md hover:bg-blue-700 transition duration-200\">\r\n");
      out.write("        Login as Manager\r\n");
      out.write("      </button>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    <!-- Demo credentials -->\r\n");
      out.write("    <p class=\"text-xs text-gray-500 mt-6 text-center\">\r\n");
      out.write("      Demo credentials:<br/>\r\n");
      out.write("      <strong>User:</strong> user@demo.com / password<br/>\r\n");
      out.write("      <strong>Manager:</strong> manager@demo.com / password\r\n");
      out.write("    </p>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- JS to toggle forms -->\r\n");
      out.write("  <script>\r\n");
      out.write("    const userBtn = document.getElementById('userBtn');\r\n");
      out.write("    const managerBtn = document.getElementById('managerBtn');\r\n");
      out.write("    const userForm = document.getElementById('userForm');\r\n");
      out.write("    const managerForm = document.getElementById('managerForm');\r\n");
      out.write("    const formTitle = document.getElementById('form-title');\r\n");
      out.write("\r\n");
      out.write("    userBtn.addEventListener('click', () => {\r\n");
      out.write("      userForm.style.display = 'block';\r\n");
      out.write("      managerForm.style.display = 'none';\r\n");
      out.write("      userBtn.classList.add('bg-white', 'text-blue-600', 'font-semibold');\r\n");
      out.write("      managerBtn.classList.remove('bg-white', 'text-blue-600', 'font-semibold');\r\n");
      out.write("      managerBtn.classList.add('text-gray-500');\r\n");
      out.write("      formTitle.innerText = 'Login to continue';\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    managerBtn.addEventListener('click', () => {\r\n");
      out.write("      userForm.style.display = 'none';\r\n");
      out.write("      managerForm.style.display = 'block';\r\n");
      out.write("      managerBtn.classList.add('bg-white', 'text-blue-600', 'font-semibold');\r\n");
      out.write("      userBtn.classList.remove('bg-white', 'text-blue-600', 'font-semibold');\r\n");
      out.write("      userBtn.classList.add('text-gray-500');\r\n");
      out.write("      formTitle.innerText = 'Manager Login';\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    function handleManagerLogin() {\r\n");
      out.write("      const username = document.getElementById('managerUsername').value;\r\n");
      out.write("      const password = document.getElementById('managerPassword').value;\r\n");
      out.write("\r\n");
      out.write("      if (username === 'manager@gmail.com' && password === 'manager') {\r\n");
      out.write("        alert('Manager login successful!');\r\n");
      out.write("        window.location.href = 'ManagerDashboard.jsp'; // redirect to dashboard\r\n");
      out.write("        return false; // stop form submission\r\n");
      out.write("      } else {\r\n");
      out.write("        alert('Invalid Manager credentials.');\r\n");
      out.write("        return false; // stop form submission\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
