/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.106
 * Generated at: 2025-07-07 04:01:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class SalesDetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Sales Details - TechParts</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        /* Basic layout */\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Segoe UI', sans-serif;\r\n");
      out.write("            background-color: #f9fafb;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            display: flex;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar {\r\n");
      out.write("            width: 220px;\r\n");
      out.write("            background-color: #111827;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 2rem 1rem;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar h2 {\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-link {\r\n");
      out.write("            color: #d1d5db;\r\n");
      out.write("            padding: 10px 15px;\r\n");
      out.write("            display: block;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            margin-bottom: 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-link:hover,\r\n");
      out.write("        .nav-link.active {\r\n");
      out.write("            background-color: #1e40af;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logout-btn {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            background-color: #ef4444;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .main {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h1 {\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sales-block {\r\n");
      out.write("            background: #ffffff;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            border: 1px solid #ddd;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            box-shadow: 0 2px 8px rgba(0,0,0,0.04);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sales-header p {\r\n");
      out.write("            margin: 4px 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        table {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border-collapse: collapse;\r\n");
      out.write("            margin-top: 12px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        th, td {\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        th {\r\n");
      out.write("            background-color: #e5e7eb;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        tr:nth-child(even) {\r\n");
      out.write("            background-color: #f3f4f6;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Sidebar -->\r\n");
      out.write("<div class=\"sidebar\">\r\n");
      out.write("    <div>\r\n");
      out.write("        <h2>TechParts</h2>\r\n");
      out.write("        <a href=\"ManagerDashboard.jsp\" class=\"nav-link\">Dashboard</a>\r\n");
      out.write("        <a href=\"Categories.jsp\" class=\"nav-link\">Categories</a>\r\n");
      out.write("        <a href=\"#\" class=\"nav-link\">Suppliers</a>\r\n");
      out.write("        <a href=\"ViewOrderDetails.jsp\" class=\"nav-link\">Orders</a>\r\n");
      out.write("        <a href=\"SalesDetails.jsp\" class=\"nav-link active\">Sales</a>\r\n");
      out.write("        <a href=\"#\" class=\"nav-link\">Reports</a>\r\n");
      out.write("        <a href=\"#\" class=\"nav-link\">Settings</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <a href=\"Login.jsp\" class=\"logout-btn\">Logout</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Main Content -->\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("    <h1>Sales Details</h1>\r\n");
      out.write("\r\n");

    Connection conn = null;
    PreparedStatement psOrders = null;
    PreparedStatement psItems = null;
    ResultSet rsOrders = null;
    ResultSet rsItems = null;

    try {
        Class.forName("com.mysql.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/computer", "root", "ishini2003");

        String sqlOrders = "SELECT * FROM orders ORDER BY id DESC";
        psOrders = conn.prepareStatement(sqlOrders);
        rsOrders = psOrders.executeQuery();

        while (rsOrders.next()) {
            int orderId = rsOrders.getInt("id");
            String name = rsOrders.getString("name");
            String email = rsOrders.getString("email");
            String phone = rsOrders.getString("phone");
            String address = rsOrders.getString("address");
            double totalAmount = rsOrders.getDouble("total_amount");

      out.write("\r\n");
      out.write("    <div class=\"sales-block\">\r\n");
      out.write("        <div class=\"sales-header\">\r\n");
      out.write("            <h2>Order ID: ");
      out.print(orderId);
      out.write("</h2>\r\n");
      out.write("            <p><strong>Customer:</strong> ");
      out.print(name);
      out.write(" | <strong>Email:</strong> ");
      out.print(email);
      out.write(" | <strong>Phone:</strong> ");
      out.print(phone);
      out.write("</p>\r\n");
      out.write("            <p><strong>Shipping Address:</strong> ");
      out.print(address);
      out.write("</p>\r\n");
      out.write("            <p><strong>Total Sale:</strong> $");
      out.print(String.format("%.2f", totalAmount));
      out.write("</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <table>\r\n");
      out.write("            <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>Product ID</th>\r\n");
      out.write("                    <th>Product Name</th>\r\n");
      out.write("                    <th>Unit Price</th>\r\n");
      out.write("                    <th>Qty</th>\r\n");
      out.write("                    <th>Total</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("            ");

                String sqlItems = "SELECT * FROM order_items WHERE order_id = ?";
                psItems = conn.prepareStatement(sqlItems);
                psItems.setInt(1, orderId);
                rsItems = psItems.executeQuery();

                while (rsItems.next()) {
                    int pid = rsItems.getInt("product_id");
                    String pname = rsItems.getString("product_name");
                    double price = rsItems.getDouble("price");
                    int qty = rsItems.getInt("quantity");
                    double total = price * qty;
            
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>");
      out.print(pid);
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print(pname);
      out.write("</td>\r\n");
      out.write("                    <td>$");
      out.print(String.format("%.2f", price));
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print(qty);
      out.write("</td>\r\n");
      out.write("                    <td>$");
      out.print(String.format("%.2f", total));
      out.write("</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            ");

                }
                rsItems.close();
                psItems.close();
            
      out.write("\r\n");
      out.write("            </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("    </div>\r\n");

        }
    } catch(Exception e) {
        out.println("<p style='color:red;'>Error: " + e.getMessage() + "</p>");
    } finally {
        try {
            if (rsOrders != null) rsOrders.close();
            if (psOrders != null) psOrders.close();
            if (conn != null) conn.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
