/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.106
 * Generated at: 2025-07-07 08:00:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Setting_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    // Load theme from session or default to "light"
    String theme = (String) session.getAttribute("theme");
    if (theme == null) theme = "light";

    // Load notification prefs from session (Boolean)
    Boolean emailNotifications = (Boolean) session.getAttribute("emailNotifications");
    Boolean smsNotifications = (Boolean) session.getAttribute("smsNotifications");
    Boolean pushNotifications = (Boolean) session.getAttribute("pushNotifications");
    // Default to false if null
    emailNotifications = (emailNotifications != null) ? emailNotifications : false;
    smsNotifications = (smsNotifications != null) ? smsNotifications : false;
    pushNotifications = (pushNotifications != null) ? pushNotifications : false;

    // Load username and email from session
    String username = (String) session.getAttribute("username");
    String email = (String) session.getAttribute("email");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <title>Settings - TechParts</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        /* Reset and base */\r\n");
      out.write("        * {\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        body {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            background-color: #f3f4f6;\r\n");
      out.write("            color: #374151;\r\n");
      out.write("            transition: background-color 0.3s, color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body.dark {\r\n");
      out.write("            background-color: #121212;\r\n");
      out.write("            color: #e0e0e0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Sidebar */\r\n");
      out.write("        .sidebar {\r\n");
      out.write("            width: 220px;\r\n");
      out.write("            background-color: #111827; /* dark slate */\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 2rem 1rem;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            transition: background-color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body.dark .sidebar {\r\n");
      out.write("            background-color: #1f2937; /* darker slate */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar h2 {\r\n");
      out.write("            margin: 0 0 2rem;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            letter-spacing: 1px;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-link {\r\n");
      out.write("            color: #d1d5db;\r\n");
      out.write("            padding: 12px 18px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            margin-bottom: 0.7rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            transition: background-color 0.3s, color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-link:hover {\r\n");
      out.write("            background-color: #1e40af;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-link.active {\r\n");
      out.write("            background-color: #2563eb;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        .logout-btn {\r\n");
      out.write("            margin-top: auto;\r\n");
      out.write("            padding: 12px 18px;\r\n");
      out.write("            background-color: #ef4444;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            display: block;\r\n");
      out.write("            user-select: none;\r\n");
      out.write("            transition: background-color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        .logout-btn:hover {\r\n");
      out.write("            background-color: #b91c1c;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Main content */\r\n");
      out.write("        .main {\r\n");
      out.write("            flex-grow: 1;\r\n");
      out.write("            padding: 3rem 4rem;\r\n");
      out.write("            overflow-y: auto;\r\n");
      out.write("            transition: color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body.dark .main {\r\n");
      out.write("            color: #d1d5db;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h1 {\r\n");
      out.write("            margin-top: 0;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("            color: #1f2937;\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("            transition: color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body.dark h1 {\r\n");
      out.write("            color: #f3f4f6;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Section styling */\r\n");
      out.write("        .section {\r\n");
      out.write("            background: white;\r\n");
      out.write("            padding: 2rem 2.5rem;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            box-shadow: 0 4px 16px rgba(0,0,0,0.1);\r\n");
      out.write("            margin-bottom: 2.5rem;\r\n");
      out.write("            transition: background-color 0.3s, box-shadow 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body.dark .section {\r\n");
      out.write("            background: #1e293b;\r\n");
      out.write("            box-shadow: 0 4px 16px rgba(0,0,0,0.6);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .section h2 {\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("            color: #111827;\r\n");
      out.write("            border-bottom: 2px solid #2563eb;\r\n");
      out.write("            padding-bottom: 0.3rem;\r\n");
      out.write("            transition: color 0.3s, border-color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body.dark .section h2 {\r\n");
      out.write("            color: #d1d5db;\r\n");
      out.write("            border-color: #3b82f6;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        label {\r\n");
      out.write("            display: block;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #374151;\r\n");
      out.write("            margin-bottom: 6px;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            transition: color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body.dark label {\r\n");
      out.write("            color: #d1d5db;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input[type=\"text\"],\r\n");
      out.write("        input[type=\"email\"],\r\n");
      out.write("        input[type=\"password\"],\r\n");
      out.write("        select {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 10px 12px;\r\n");
      out.write("            border: 1.8px solid #d1d5db;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            transition: border-color 0.25s, background-color 0.3s, color 0.3s;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            color: #111827;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body.dark input[type=\"text\"],\r\n");
      out.write("        body.dark input[type=\"email\"],\r\n");
      out.write("        body.dark input[type=\"password\"],\r\n");
      out.write("        body.dark select {\r\n");
      out.write("            background-color: #334155;\r\n");
      out.write("            color: #e0e0e0;\r\n");
      out.write("            border-color: #475569;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input[type=\"text\"]:focus,\r\n");
      out.write("        input[type=\"email\"]:focus,\r\n");
      out.write("        input[type=\"password\"]:focus,\r\n");
      out.write("        select:focus {\r\n");
      out.write("            outline: none;\r\n");
      out.write("            border-color: #2563eb;\r\n");
      out.write("            box-shadow: 0 0 5px #2563eb;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Checkbox group */\r\n");
      out.write("        .checkbox-group {\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .checkbox-group label {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            font-weight: normal;\r\n");
      out.write("            margin-right: 20px;\r\n");
      out.write("            color: #4b5563;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        body.dark .checkbox-group label {\r\n");
      out.write("            color: #9ca3af;\r\n");
      out.write("        }\r\n");
      out.write("        .checkbox-group input[type=\"checkbox\"] {\r\n");
      out.write("            margin-right: 6px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        button[type=\"submit\"] {\r\n");
      out.write("            margin-top: 2rem;\r\n");
      out.write("            background-color: #2563eb;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 12px 20px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: background-color 0.3s;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("        }\r\n");
      out.write("        button[type=\"submit\"]:hover {\r\n");
      out.write("            background-color: #1e40af;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Danger button */\r\n");
      out.write("        .btn-danger {\r\n");
      out.write("            background-color: #ef4444;\r\n");
      out.write("            margin-top: 1rem;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 12px 20px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: white;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            transition: background-color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-danger:hover {\r\n");
      out.write("            background-color: #b91c1c;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Helper text */\r\n");
      out.write("        .helper-text {\r\n");
      out.write("            font-size: 0.875rem;\r\n");
      out.write("            color: #6b7280;\r\n");
      out.write("            margin-top: 4px;\r\n");
      out.write("            transition: color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body.dark .helper-text {\r\n");
      out.write("            color: #9ca3af;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive */\r\n");
      out.write("        @media (max-width: 720px) {\r\n");
      out.write("            body {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                height: auto;\r\n");
      out.write("            }\r\n");
      out.write("            .sidebar {\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                flex-direction: row;\r\n");
      out.write("                padding: 1rem;\r\n");
      out.write("                overflow-x: auto;\r\n");
      out.write("            }\r\n");
      out.write("            .sidebar h2 {\r\n");
      out.write("                flex: 1 0 auto;\r\n");
      out.write("                margin-bottom: 0;\r\n");
      out.write("            }\r\n");
      out.write("            .nav-link {\r\n");
      out.write("                margin: 0 10px 0 0;\r\n");
      out.write("                padding: 8px 12px;\r\n");
      out.write("            }\r\n");
      out.write("            .logout-btn {\r\n");
      out.write("                margin: 0 0 0 auto;\r\n");
      out.write("                padding: 8px 12px;\r\n");
      out.write("            }\r\n");
      out.write("            .main {\r\n");
      out.write("                padding: 2rem 1.5rem;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"");
      out.print( theme );
      out.write("\">\r\n");
      out.write("    <div class=\"sidebar\">\r\n");
      out.write("        <h2>TechParts</h2>\r\n");
      out.write("        <a href=\"ManagerDashboard.jsp\" class=\"nav-link\">Dashboard</a>\r\n");
      out.write("        <a href=\"Categories.jsp\" class=\"nav-link\">Categories</a>\r\n");
      out.write("        <a href=\"SupplierDetails.jsp\" class=\"nav-link\">Suppliers</a>\r\n");
      out.write("        <a href=\"ViewOrderDetails.jsp\" class=\"nav-link\">Orders</a>\r\n");
      out.write("        <a href=\"SalesDetails.jsp\" class=\"nav-link\">Sales</a>\r\n");
      out.write("        <a href=\"Settings.jsp\" class=\"nav-link active\">Settings</a>\r\n");
      out.write("        <a href=\"Login.jsp\" class=\"logout-btn\">Logout</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"main\">\r\n");
      out.write("        <h1>Settings</h1>\r\n");
      out.write("\r\n");
      out.write("        <!-- Profile Info -->\r\n");
      out.write("        <section class=\"section\">\r\n");
      out.write("            <h2>Profile Information</h2>\r\n");
      out.write("            <form action=\"UpdateSettingsServlet\" method=\"post\">\r\n");
      out.write("                <label for=\"username\">Username</label>\r\n");
      out.write("                <input type=\"text\" id=\"username\" name=\"username\" value=\"");
      out.print( username != null ? username : "" );
      out.write("\" required />\r\n");
      out.write("\r\n");
      out.write("                <label for=\"email\">Email Address</label>\r\n");
      out.write("                <input type=\"email\" id=\"email\" name=\"email\" value=\"");
      out.print( email != null ? email : "" );
      out.write("\" required />\r\n");
      out.write("\r\n");
      out.write("                <label for=\"currentPassword\">Current Password</label>\r\n");
      out.write("                <input type=\"password\" id=\"currentPassword\" name=\"currentPassword\" placeholder=\"Enter current password to save changes\" />\r\n");
      out.write("\r\n");
      out.write("                <label for=\"newPassword\">New Password</label>\r\n");
      out.write("                <input type=\"password\" id=\"newPassword\" name=\"newPassword\" placeholder=\"Leave blank to keep current password\" />\r\n");
      out.write("\r\n");
      out.write("                <button type=\"submit\">Update Profile</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <!-- Notifications -->\r\n");
      out.write("        <section class=\"section\">\r\n");
      out.write("            <h2>Notification Preferences</h2>\r\n");
      out.write("            <form action=\"UpdateNotificationsServlet\" method=\"post\">\r\n");
      out.write("                <div class=\"checkbox-group\">\r\n");
      out.write("                    <label>\r\n");
      out.write("                        <input type=\"checkbox\" name=\"emailNotifications\" ");
      out.print( emailNotifications ? "checked" : "" );
      out.write(" />\r\n");
      out.write("                        Email Notifications\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <label>\r\n");
      out.write("                        <input type=\"checkbox\" name=\"smsNotifications\" ");
      out.print( smsNotifications ? "checked" : "" );
      out.write(" />\r\n");
      out.write("                        SMS Notifications\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <label>\r\n");
      out.write("                        <input type=\"checkbox\" name=\"pushNotifications\" ");
      out.print( pushNotifications ? "checked" : "" );
      out.write(" />\r\n");
      out.write("                        Push Notifications\r\n");
      out.write("                    </label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button type=\"submit\">Update Notifications</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <!-- Appearance -->\r\n");
      out.write("        <section class=\"section\">\r\n");
      out.write("            <h2>Appearance</h2>\r\n");
      out.write("            <form action=\"UpdateAppearanceServlet\" method=\"post\">\r\n");
      out.write("                <label for=\"theme\">Select Theme</label>\r\n");
      out.write("                <select id=\"theme\" name=\"theme\">\r\n");
      out.write("                    <option value=\"light\" ");
      out.print( "light".equals(theme) ? "selected" : "" );
      out.write(">Light</option>\r\n");
      out.write("                    <option value=\"dark\" ");
      out.print( "dark".equals(theme) ? "selected" : "" );
      out.write(">Dark</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                <button type=\"submit\">Update Appearance</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <!-- Danger Zone -->\r\n");
      out.write("        <section class=\"section\">\r\n");
      out.write("            <h2>Danger Zone</h2>\r\n");
      out.write("            <p class=\"helper-text\">Deleting your account is irreversible. Please proceed with caution.</p>\r\n");
      out.write("            <form action=\"DeleteAccountServlet\" method=\"post\" onsubmit=\"return confirm('Are you sure you want to delete your account? This action cannot be undone.')\">\r\n");
      out.write("                <button type=\"submit\" class=\"btn-danger\">Delete Account</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </section>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
