/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.106
 * Generated at: 2025-07-06 05:04:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import ComputerPackage.CartItem;

public final class ViewCart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("ComputerPackage.CartItem");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Your Cart - TechParts</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            background: #f9fafb;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .header {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 20px 40px;\r\n");
      out.write("            background: white;\r\n");
      out.write("            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo h2 {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            color: #2563eb;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-links {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 25px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-links a {\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: #374151;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dropdown {\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dropbtn {\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            color: #374151;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dropdown-content {\r\n");
      out.write("            display: none;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            min-width: 220px;\r\n");
      out.write("            top: 30px;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            box-shadow: 0px 8px 16px rgba(0, 0, 0, 0.15);\r\n");
      out.write("            z-index: 999;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dropdown-content a {\r\n");
      out.write("            color: #333;\r\n");
      out.write("            padding: 12px 16px;\r\n");
      out.write("            display: block;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dropdown:hover .dropdown-content {\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cart {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: inherit;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cart-count {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: -10px;\r\n");
      out.write("            right: -10px;\r\n");
      out.write("            background: red;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-size: 10px;\r\n");
      out.write("            width: 16px;\r\n");
      out.write("            height: 16px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-btn a {\r\n");
      out.write("            background: #2563eb;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 8px 16px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h2 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #1f2937;\r\n");
      out.write("            margin-top: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        table {\r\n");
      out.write("            width: 90%;\r\n");
      out.write("            margin: 30px auto;\r\n");
      out.write("            border-collapse: collapse;\r\n");
      out.write("            background: white;\r\n");
      out.write("            box-shadow: 0 4px 8px rgba(0,0,0,0.05);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        th, td {\r\n");
      out.write("            padding: 12px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            border-bottom: 1px solid #e5e7eb;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        th {\r\n");
      out.write("            background-color: #2563eb;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        img {\r\n");
      out.write("            width: 80px;\r\n");
      out.write("            height: auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .remove-btn {\r\n");
      out.write("            background: #ef4444;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 6px 12px;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .remove-btn:hover {\r\n");
      out.write("            background: #dc2626;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .qty-form button {\r\n");
      out.write("            padding: 2px 8px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            background-color: #d1d5db;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .qty-form button:hover {\r\n");
      out.write("            background-color: #9ca3af;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .total {\r\n");
      out.write("            text-align: right;\r\n");
      out.write("            width: 90%;\r\n");
      out.write("            margin: 20px auto;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: #111827;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .checkout-btn {\r\n");
      out.write("            display: block;\r\n");
      out.write("            width: 220px;\r\n");
      out.write("            margin: 20px auto;\r\n");
      out.write("            background-color: #10b981;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 12px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .checkout-btn:hover {\r\n");
      out.write("            background-color: #059669;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .empty-message {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-top: 100px;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            color: #6b7280;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .empty-message a {\r\n");
      out.write("            color: #2563eb;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .empty-message a:hover {\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- â Navbar -->\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("    <div class=\"logo\">\r\n");
      out.write("        <img src=\"images/logo.png\" alt=\"logo\" width=\"40\" height=\"40\">\r\n");
      out.write("        <h2>TechParts</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"nav-links\">\r\n");
      out.write("        <a href=\"Home.jsp\">Home</a>\r\n");
      out.write("        <a href=\"AboutUs.jsp\">About Us</a>\r\n");
      out.write("        <div class=\"dropdown\">\r\n");
      out.write("            <span class=\"dropbtn\">All Products</span>\r\n");
      out.write("            <div class=\"dropdown-content\">\r\n");
      out.write("                <a href=\"Laptops.jsp\">Laptops</a>\r\n");
      out.write("                <a href=\"laptopAccessories.jsp\">Laptop Accessories</a>\r\n");
      out.write("                <a href=\"desktopAccessories.jsp\">Desktop & Accessories</a>\r\n");
      out.write("                <a href=\"cctv.jsp\">CCTV Camera & Accessories</a>\r\n");
      out.write("                <a href=\"cameraItems.jsp\">Camera Items</a>\r\n");
      out.write("                <a href=\"printers.jsp\">Printers</a>\r\n");
      out.write("                <a href=\"giftVouchers.jsp\">Gift Vouchers</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a href=\"Services.jsp\">Services</a>\r\n");
      out.write("        <a href=\"Paymentmethod.jsp\">Payment Methods</a>\r\n");
      out.write("        <a href=\"Contactus.jsp\">Contact Us</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div style=\"display: flex; align-items: center; gap: 15px;\">\r\n");
      out.write("        <a href=\"ViewCart.jsp\" class=\"cart\">\r\n");
      out.write("            ð\r\n");
      out.write("            ");

                List<CartItem> cart = (List<CartItem>) session.getAttribute("cart");
                int count = 0;
                if (cart != null) {
                    for (CartItem item : cart) {
                        count += item.getQuantity();
                    }
                }
            
      out.write("\r\n");
      out.write("            <span class=\"cart-count\">");
      out.print( count );
      out.write("</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"login-btn\">\r\n");
      out.write("            <a href=\"Login.jsp\">Login</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- â Cart Content -->\r\n");
      out.write("<h2>Your Shopping Cart</h2>\r\n");
      out.write("\r\n");

    double total = 0;
    if (cart != null && !cart.isEmpty()) {

      out.write("\r\n");
      out.write("    <table>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <th>Image</th>\r\n");
      out.write("            <th>Product</th>\r\n");
      out.write("            <th>Price (Rs)</th>\r\n");
      out.write("            <th>Quantity</th>\r\n");
      out.write("            <th>Subtotal</th>\r\n");
      out.write("            <th>Action</th>\r\n");
      out.write("        </tr>\r\n");
      out.write("        ");

            for (CartItem item : cart) {
                double sub = item.getPrice() * item.getQuantity();
                total += sub;
        
      out.write("\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td><img src=\"");
      out.print( item.getImage() );
      out.write("\" alt=\"Product\"></td>\r\n");
      out.write("            <td>");
      out.print( item.getName() );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print( String.format("%.2f", item.getPrice()) );
      out.write("</td>\r\n");
      out.write("            <td>\r\n");
      out.write("                <form action=\"UpdateCartServlet\" method=\"post\" class=\"qty-form\" style=\"display:inline;\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"id\" value=\"");
      out.print( item.getId() );
      out.write("\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"action\" value=\"decrement\">\r\n");
      out.write("                    <button type=\"submit\">-</button>\r\n");
      out.write("                </form>\r\n");
      out.write("                <span style=\"margin: 0 10px;\">");
      out.print( item.getQuantity() );
      out.write("</span>\r\n");
      out.write("                <form action=\"UpdateCartServlet\" method=\"post\" class=\"qty-form\" style=\"display:inline;\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"id\" value=\"");
      out.print( item.getId() );
      out.write("\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"action\" value=\"increment\">\r\n");
      out.write("                    <button type=\"submit\">+</button>\r\n");
      out.write("                </form>\r\n");
      out.write("            </td>\r\n");
      out.write("            <td>");
      out.print( String.format("%.2f", sub) );
      out.write("</td>\r\n");
      out.write("            <td>\r\n");
      out.write("                <form action=\"RemoveFromCartServlet\" method=\"post\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"id\" value=\"");
      out.print( item.getId() );
      out.write("\">\r\n");
      out.write("                    <button class=\"remove-btn\" type=\"submit\">Remove</button>\r\n");
      out.write("                </form>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </table>\r\n");
      out.write("\r\n");
      out.write("    <p class=\"total\">Total: Rs. ");
      out.print( String.format("%.2f", total) );
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("    <form action=\"Checkout.jsp\">\r\n");
      out.write("        <button class=\"checkout-btn\">Proceed to Checkout</button>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
 } else { 
      out.write("\r\n");
      out.write("    <div class=\"empty-message\">\r\n");
      out.write("        Your cart is empty. <br><br>\r\n");
      out.write("        <a href=\"Laptops.jsp\">Start Shopping â</a>\r\n");
      out.write("    </div>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
