/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.106
 * Generated at: 2025-07-03 15:06:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class ViewCctvAccess_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>View CCTV Accessories - TechParts</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Segoe UI', sans-serif;\r\n");
      out.write("            background-color: #f9fafb;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h2 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #1f2937;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .add-button {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            background-color: #2563eb;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 10px 18px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .add-button:hover {\r\n");
      out.write("            background-color: #1e40af;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        table {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border-collapse: collapse;\r\n");
      out.write("            background: white;\r\n");
      out.write("            box-shadow: 0 2px 8px rgba(0,0,0,0.1);\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        th, td {\r\n");
      out.write("            padding: 14px 18px;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            border-bottom: 1px solid #e5e7eb;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        th {\r\n");
      out.write("            background-color: #111827;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        tr:hover {\r\n");
      out.write("            background-color: #f1f5f9;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .actions a {\r\n");
      out.write("            padding: 6px 12px;\r\n");
      out.write("            margin-right: 8px;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .edit-btn {\r\n");
      out.write("            background-color: #10b981;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .delete-btn {\r\n");
      out.write("            background-color: #ef4444;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .image-thumb {\r\n");
      out.write("            width: 60px;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            object-fit: contain;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .back-link {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            color: #2563eb;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .back-link:hover {\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .desc-cell {\r\n");
      out.write("            max-width: 300px;\r\n");
      out.write("            white-space: nowrap;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            text-overflow: ellipsis;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div style=\"display: flex; justify-content: space-between; margin-bottom: 20px;\">\r\n");
      out.write("    <a href=\"Categories.jsp\" class=\"add-button\" style=\"background-color: #6b7280;\"> Back to Categories</a>\r\n");
      out.write("    <a href=\"AddCCTVAcces.jsp\" class=\"add-button\"> Add CCTV Accessory</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<h2>CCTV Accessories List</h2>\r\n");
      out.write("\r\n");

    try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/computer", "root", "ishini2003");

        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery("SELECT * FROM cctvaccess WHERE category='CCTV Accessory'");

        if (rs.next()) {

      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("    <tr>\r\n");
      out.write("        <th>ID</th>\r\n");
      out.write("        <th>Image</th>\r\n");
      out.write("        <th>Item Code</th>\r\n");
      out.write("        <th>Name</th>\r\n");
      out.write("        <th>Brand</th>\r\n");
      out.write("        <th>Price</th>\r\n");
      out.write("        <th>Cash Price</th>\r\n");
      out.write("        <th>Status</th>\r\n");
      out.write("        <th>Description</th>\r\n");
      out.write("        <th>Actions</th>\r\n");
      out.write("    </tr>\r\n");
      out.write("    ");

        do {
    
      out.write("\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td>");
      out.print( rs.getInt("id") );
      out.write("</td>\r\n");
      out.write("        <td><img src=\"");
      out.print( rs.getString("image_url") );
      out.write("\" alt=\"Image\" class=\"image-thumb\"></td>\r\n");
      out.write("        <td>");
      out.print( rs.getString("item_code") );
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print( rs.getString("name") );
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print( rs.getString("brand") );
      out.write("</td>\r\n");
      out.write("        <td>Rs. ");
      out.print( rs.getDouble("price") );
      out.write("</td>\r\n");
      out.write("        <td>Rs. ");
      out.print( rs.getDouble("cash_price") );
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print( rs.getString("stock_status") );
      out.write("</td>\r\n");
      out.write("        <td class=\"desc-cell\">");
      out.print( rs.getString("description") );
      out.write("</td>\r\n");
      out.write("        <td class=\"actions\">\r\n");
      out.write("            <a href=\"EditCctvAccessory.jsp?id=");
      out.print( rs.getInt("id") );
      out.write("\" class=\"edit-btn\">Edit</a>\r\n");
      out.write("            <a href=\"DeleteCctvAccessServlet?id=");
      out.print( rs.getInt("id") );
      out.write("\" class=\"delete-btn\" onclick=\"return confirm('Are you sure you want to delete this accessory?');\">Delete</a>\r\n");
      out.write("        </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    ");

        } while (rs.next());
    
      out.write("\r\n");
      out.write("</table>\r\n");
 
    } else {
        out.println("<p style='text-align:center;'>No CCTV accessories found.</p>");
    }

    rs.close();
    stmt.close();
    conn.close();
} catch (Exception e) {
    out.println("<p style='color:red;'>Error: " + e.getMessage() + "</p>");
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
